baseURL: https://www.pablomarcos.me

languageCode: en-us
title: "Pablo Marcos' Blog"
theme: "toha"

# Manage languages
# For any more details, you can check the official documentation: https://gohugo.io/content-management/multilingual/
languages:
  en:
    languageName: English
    weight: 1
  es:
    languageName: Español
    weight: 2
  fr:
    languageName: Français
    weight: 3
    
# At least HTML and JSON are required for the main HTML content and
# client-side JavaScript search
outputs:
  home:
    - HTML
    - RSS
    - JSON    

# Control TOC depth
markup:
  goldmark:
    renderer:
      unsafe: true
  tableOfContents:
    startLevel: 2
    endLevel: 6
    ordered: false

# Enable global emoji support
enableEmoji: true

# Site parameters
params:
  #Background IMG for your page
  background: "/images/site/background.png"
  
  # GitHub repo URL of your site
  gitRepo: https://codeberg.org/FlyingFlamingo/pablomarcos.me/

  # specify whether you want to write some blog posts or not
  enableBlogPost: false

  # specify whether you want to show Table of Contents in reading page
  enableTOC: true

  # Provide newsletter configuration. This feature hasn't been implemented yet.
  # Currently, you can just hide it from the footer.
  newsletter:
    enable: true
  #Add custom logos and favicon
  logo:
    main: "images/main-logo.png"
    inverted: "images/inverted-logo.png"
    favicon: "images/new-favicon.png"
